#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Configurable Starting Prompt Feature

set -e

echo "========================================"
echo "Starting A.D.A V2 Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project Root
PROJECT_ROOT="/Users/gglazer/Projects/ada_v2"
cd "$PROJECT_ROOT"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# ACTIVATE CONDA ENVIRONMENT
# ============================================

echo ""
echo "Activating conda environment: ada_v2"
# Note: This script should be sourced or run in a conda-initialized shell
# If conda is not available, the npm run dev command will handle backend startup

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting development servers..."
echo "This will start both backend (port 8000) and frontend (port 5173)"
echo ""

# The npm run dev script handles starting both backend and frontend
# via concurrently (see package.json)
npm run dev &
NPM_PID=$!

# Wait for services
wait_for_service 8000 "Backend (FastAPI + Socket.IO)"
wait_for_service 5173 "Frontend (Vite + React)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend:  http://localhost:8000"
echo "  Frontend: http://localhost:5173"
echo "  API Docs: http://localhost:8000/docs"
echo ""
echo "To stop: Press Ctrl+C or kill PID $NPM_PID"
echo ""

# Keep script running
wait $NPM_PID
